### ISSUE TITLE
How to ungroup the grouped .hbs templates in .yaml file in metalsmith pattern collection

### ISSUE THREAD

**Issue by ayusman33** [metalsmith/collections#95]
A yaml file for example:
```yaml
---
title: Test
page-key: test
hierarchy: atom
status: Ready
layout: test-example.hbs
group: Testing
---
```

With this when I call the pattern in buildHtml.js:
```js
'Name': {
    pattern: '/components/**/*.yaml',
    sortBy: sortByGroupAndPageKey,
},
```

This results in showing the link as an accordion group name. Now this does not show the component link/path directly on the page. So I want to have ungrouped this kind of yaml files and then display without accordion grouping.
